# 集群的时候 spring.application.name 要一致，否则会出现不可用的复制品 ，见图 unavailable-replicas.png
spring.application.name=spring-cloud-eureka
server.port=8001
eureka.instance.hostname=peer1

# 这里用 http://localhost:8002/eureka/ 也是不行的，为啥这样？不知道
eureka.client.serviceUrl.defaultZone=http://peer2:8002/eureka/




# 老老实实在host文件增加下面几个，host文件可能不允许保存，修改一下只读属性
# 127.0.0.1 peer1
# 127.0.0.1 peer2
# 127.0.0.1 peer3
# 127.0.0.1 peer4
